### ISSUE TITLE
Add mumble server

### ISSUE THREAD

**Issue by bhanuvrat** [pydelhi/pydelhi-infra#14]
mumble is used by the hillhacks community for conference calls.
it performed much better in a test run compared to hangouts.
shall we setup an instance on pydelhi.org or just go around highjacking hillhack's channel ;) ?

Reference: http://wiki.mumble.info/wiki/Installing_Mumble#Linux

**Comment by CuriousLearner** [comment]
Let's give it a try on hillhack's channel probably in the next Thursday call and if everyone finds it good, we can set it up on pydelhi.org

**Comment by bhanuvrat** [comment]
so .. I just got told off by Bernadette (sva.b) over there :( 
lets setup our own ...
